# Generated by Django 4.2.2 on 2023-06-23 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accademics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accademics',
            options={'verbose_name_plural': 'Les accademies dans AHSM'},
        ),
    ]
