# Generated by Django 4.2.2 on 2023-06-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accademics', '0002_alter_accademics_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accademics',
            name='type',
            field=models.CharField(choices=[('A', 'Tesol'), ('B', 'Bacc National'), ('C', 'Bacc American')], max_length=1, null=True),
        ),
    ]
