# Generated by Django 4.2.2 on 2023-07-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accademics', '0003_accademics_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accademics',
            table='accademic',
        ),
    ]
