# Generated by Django 4.2.3 on 2023-07-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accademics', '0004_alter_accademics_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accademics',
            options={'ordering': ['type'], 'verbose_name_plural': 'Les accademies dans AHSM'},
        ),
        migrations.AlterField(
            model_name='accademics',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
    ]
