# Generated by Django 4.2.2 on 2023-06-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_price_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='value',
        ),
    ]
