# Generated by Django 4.2.2 on 2023-06-23 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_rename_price_price_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='prices',
        ),
        migrations.AddField(
            model_name='price',
            name='levels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='price.level'),
        ),
    ]
