# Generated by Django 4.2.2 on 2023-06-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_remove_level_prices_price_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='levels',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='price.level'),
        ),
    ]
