---
defaults: &defaults
  deploy_path: /home/ittiamer/public_html/
#  github_path: /home/ittiamer/repositories/American-HighSchool/
  activate_command: /bin/bash -c "source /home/ittiamer/virtualenv/repositories/American-HighSchool/3.11/bin/activate"

deployment:
  tasks:
    - export DEPLOYPATH=${defaults.deploy_path}
#    - export GITHUBPATH=${defaults.github_path}
    - ${defaults.activate_command} && pip install -r requirements.txt
    - ${defaults.activate_command} && python manage.py collectstatic --noinput
    - ${defaults.activate_command} && python manage.py migrate --noinput
#    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp * $DEPLOYPATH