---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ittiamer/public_html
    - export GITHUBPATH=/home/ittiamer/repositories/American-HighSchool  # Chemin de déploiement
    - /bin/bash -c "source /home/ittiamer/virtualenv/repositories/American-HighSchool/3.11/bin/activate && pip install -r $GITHUBPATH/requirements.txt"  # Installation des dépendances depuis requirements.txt
    - /bin/bash -c "source /home/ittiamer/virtualenv/repositories/American-HighSchool/3.11/bin/activate && python $GITHUBPATH/manage.py collectstatic --noinput"  # Collecte des fichiers statiques
    - /bin/bash -c "source /home/ittiamer/virtualenv/repositories/American-HighSchool/3.11/bin/activate && python $GITHUBPATH/manage.py migrate --noinput"  # Exécution des migrations
    - /bin/cp -a $GITHUBPATH/static $DEPLOYPATH  # Copie des fichiers statiques
    - /bin/cp -a $GITHUBPATH/staticfiles $DEPLOYPATH  # Copie des fichiers staticfiles
