# Generated by Django 4.2.2 on 2023-07-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactclient',
            table='contact_client',
        ),
        migrations.AlterModelTable(
            name='contacthelp',
            table='contact_help',
        ),
        migrations.AlterModelTable(
            name='contactus',
            table='contact_us',
        ),
        migrations.AlterModelTable(
            name='social',
            table='social',
        ),
    ]
