# Generated by Django 4.2.2 on 2023-06-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='libel',
            field=models.TextField(max_length=250),
        ),
    ]
