# Generated by Django 4.2.2 on 2023-06-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_presentationimage_presentationvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
    ]
