# Generated by Django 4.2.2 on 2023-06-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_hour_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='day',
            field=models.CharField(choices=[('Monday', 'Lundi'), ('Tuesday', 'Mardi'), ('Wednesday', 'Mercredi'), ('Thursday', 'Jeudi'), ('Friday', 'Vendredi'), ('Saturday', 'Samedi'), ('Sunday', 'Dimanche')], max_length=15, unique=True),
        ),
    ]
