# Generated by Django 4.2.2 on 2023-06-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_address_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutlist',
            options={'verbose_name_plural': 'A Propos : Listes'},
        ),
    ]
