# Generated by Django 4.2.2 on 2023-06-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_hour_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='day',
            field=models.CharField(choices=[('mon', 'Lundi'), ('tue', 'Mardi'), ('wed', 'Mercredi'), ('thu', 'Jeudi'), ('fri', 'Vendredi'), ('sat', 'Samedi'), ('sun', 'Dimanche')], max_length=15, unique=True),
        ),
    ]
