# Generated by Django 4.2.2 on 2023-06-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_aboutlist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('fa fa-envelope', 'Email'), ('fa fa-phone-alt', 'Phone'), ('fa fa-whatsapp', 'WhatsApp')], max_length=25),
        ),
    ]
