# Generated by Django 4.2.2 on 2023-06-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('fa fa-envelope text-primary me-2', 'Email'), ('fa fa-phone-alt text-primary me-2', 'Phone'), ('fa fa-whatsapp text-primary me-2', 'WhatsApp')], max_length=50),
        ),
    ]
