# Generated by Django 4.2.2 on 2023-06-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_hour_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hour',
            name='active',
        ),
        migrations.RemoveField(
            model_name='hour',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hour',
            name='updated_at',
        ),
    ]
