# Generated by Django 4.2.2 on 2023-06-19 09:41

import app.constants
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(blank=True, default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])])),
                ('name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='info_line',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('fa fa-envelope text-primary me-2', 'Email'), ('fa fa-phone text-primary me-2', 'Phone'), ('fa fa-whatsapp text-primary me-2', 'WhatsApp')], max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='all_service',
            field=models.ManyToManyField(null=True, to='app.servicetype', verbose_name='Tout les Services'),
        ),
    ]
