# Generated by Django 4.2.2 on 2023-06-20 12:42

import app.constants
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_hour_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='image',
        ),
        migrations.AddField(
            model_name='price',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='presentationimage',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='vision',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
    ]
