# Generated by Django 4.2.2 on 2023-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_servicetype_remove_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='key',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
