# Generated by Django 4.2.2 on 2023-06-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_level_image_price_image_alter_about_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='registration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
