# Generated by Django 4.2.2 on 2023-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_service_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
