# Generated by Django 4.2.2 on 2023-06-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_service_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='category',
            field=models.CharField(choices=[('A', 'Direction'), ('B', 'Administrative'), ('C', 'Enseignants ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
