# Generated by Django 4.2.2 on 2023-06-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_members_category_alter_members_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='category',
            field=models.CharField(choices=[('A', 'Direction'), ('B', 'Administrative'), ('C', 'Enseignants ')], max_length=2, null=True),
        ),
    ]
