# Generated by Django 4.2.2 on 2023-06-19 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'Contact Info'},
        ),
        migrations.RemoveField(
            model_name='price',
            name='possibilities',
        ),
        migrations.AlterField(
            model_name='price',
            name='promotion',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
