# Generated by Django 4.2.2 on 2023-06-19 17:55

import app.constants
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_info_level_delete_contactinfo_delete_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accreditation',
            options={'verbose_name_plural': 'Les Accreditations'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Les Activités'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Les Adresses'},
        ),
        migrations.AlterModelOptions(
            name='collaborator',
            options={'verbose_name_plural': 'Les Collaborateurs'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Les Contacts'},
        ),
        migrations.AlterModelOptions(
            name='hour',
            options={'verbose_name_plural': 'Les Horaires'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'Les Informations lier à AHSM'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name_plural': 'Les Levels'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name_plural': 'Les Membres'},
        ),
        migrations.AlterModelOptions(
            name='possibility',
            options={'verbose_name_plural': 'Les Possibilités'},
        ),
        migrations.AlterModelOptions(
            name='presentationimage',
            options={'verbose_name_plural': 'La Présentation Photo'},
        ),
        migrations.AlterModelOptions(
            name='presentationvideo',
            options={'verbose_name_plural': 'La Présentation Vidéo'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name_plural': 'Les Prix'},
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name_plural': 'Les Démandes Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name_plural': 'Les Réseau Sociaux'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': 'Les Témoignages'},
        ),
        migrations.AlterModelOptions(
            name='vision',
            options={'verbose_name_plural': 'Les Visions'},
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='presentationimage',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='presentationvideo',
            name='video',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='vision',
            name='image',
            field=models.FileField(default='', null=True, upload_to=app.constants.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])]),
        ),
    ]
