# Generated by Django 4.2.2 on 2023-06-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_accreditation_options_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'Les Propos'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Les Adrèsses'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name_plural': 'Les Niveaux'},
        ),
    ]
