# Generated by Django 4.2.2 on 2023-06-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_about_options_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Les Services'},
        ),
    ]
