# Generated by Django 4.2.2 on 2023-07-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accreditation',
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
