# Generated by Django 4.2.3 on 2023-07-13 09:15

import Web.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_delete_accreditation_delete_collaborator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(default='', null=True, upload_to=Web.utils.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])])),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': "L'Image des membres",
                'db_table': 'all_member',
            },
        ),
    ]
