# Generated by Django 4.2.2 on 2023-06-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_slogan_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='slogan',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
