# Generated by Django 4.2.2 on 2023-07-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_slogan_note'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='blog',
        ),
        migrations.AlterModelTable(
            name='slogan',
            table='slogan',
        ),
    ]
