# Generated by Django 4.2.2 on 2023-06-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name_plural': 'Les Enregistrements de nouveau étudiant'},
        ),
    ]
