# Generated by Django 4.2.2 on 2023-06-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15)),
                ('contact_type', models.CharField(choices=[('fa-envelope', 'Email'), ('fa-phone-alt', 'Phone'), ('fa-whatsapp', 'WhatsApp')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=200)),
                ('social_type', models.CharField(choices=[('fa-linkedin-in', 'LinkedIn'), ('fa-twitter', 'Twitter'), ('fa-facebook-f', 'Facebook'), ('fa-instagram', 'Instagram')], max_length=25)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=250)),
                ('day_begin', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('day_end', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('time_begin', models.TimeField()),
                ('time_end', models.TimeField()),
                ('contacts', models.ManyToManyField(to='home.contact')),
                ('socials', models.ManyToManyField(to='home.social')),
            ],
        ),
    ]
