# Generated by Django 4.2.3 on 2023-07-13 10:26

import Web.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(default='', null=True, upload_to=Web.utils.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])])),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Les Activités extra-scolaires',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='PresentationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(default='', null=True, upload_to=Web.utils.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])])),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Les Présentations Photo AHSM',
                'db_table': 'p_image',
            },
        ),
        migrations.CreateModel(
            name='PresentationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(default='', upload_to=Web.utils.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov'])])),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Les Présentations Vidéo AHSM',
                'db_table': 'p_video',
            },
        ),
    ]
