# Generated by Django 4.2.2 on 2023-06-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
