# Generated by Django 4.2.2 on 2023-07-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_possibility'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='presentationimage',
            table='p_image',
        ),
        migrations.AlterModelTable(
            name='presentationvideo',
            table='p_video',
        ),
    ]
