# Generated by Django 4.2.2 on 2023-06-16 06:44

import django.core.validators
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(default='')),
                ('file', models.FileField(upload_to=home.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
            ],
        ),
        migrations.RemoveField(
            model_name='information',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='information',
            name='socials',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
