# Generated by Django 4.2.2 on 2023-07-01 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addressahsm',
            table='address_ahsm',
        ),
    ]
