# Generated by Django 4.2.3 on 2023-07-13 10:26

import Web.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('libel', models.TextField(blank=True, default=' ', null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('A', 'Mission'), ('B', 'Vision')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Les Missions et Visions',
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='AboutAHSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(default='', null=True, upload_to=Web.utils.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])])),
                ('title', models.CharField(max_length=150)),
                ('key', models.CharField(max_length=100)),
                ('libel', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Les Informations sur AHSH',
                'db_table': 'about_ahsm',
            },
        ),
        migrations.CreateModel(
            name='AboutITTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Les Informations sur ITTI',
                'db_table': 'about_itti',
            },
        ),
        migrations.CreateModel(
            name='AboutHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('contacts', models.ManyToManyField(related_name='about_to_contact', to='contact.contacthelp')),
            ],
            options={
                'verbose_name_plural': "Les Supports d'Aide Client (About) ",
                'db_table': 'about_help',
            },
        ),
    ]
