# Generated by Django 4.2.2 on 2023-06-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutitti',
            options={'verbose_name_plural': 'Les Informations sur ITTI'},
        ),
    ]
