# Generated by Django 4.2.2 on 2023-06-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'Les Missions et Visions'},
        ),
    ]
