# Generated by Django 4.2.2 on 2023-06-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_about_libel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='libel',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
