# Generated by Django 4.2.2 on 2023-07-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_about_libel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'about_us', 'verbose_name_plural': 'Les Missions et Visions'},
        ),
        migrations.AlterModelOptions(
            name='aboutahsm',
            options={'verbose_name': 'about_ahsm', 'verbose_name_plural': 'Les Informations sur AHSH'},
        ),
        migrations.AlterModelOptions(
            name='abouthelp',
            options={'verbose_name': 'about_help', 'verbose_name_plural': "Les Supports d'Aide Client (About) "},
        ),
        migrations.AlterModelOptions(
            name='aboutitti',
            options={'verbose_name': 'about_itti', 'verbose_name_plural': 'Les Informations sur ITTI'},
        ),
    ]
