# Generated by Django 4.2.2 on 2023-07-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactclient_table_alter_contacthelp_table_and_more'),
        ('about', '0011_alter_about_options_alter_aboutahsm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthelp',
            name='contacts',
            field=models.ManyToManyField(related_name='about_to_contact', to='contact.contacthelp'),
        ),
    ]
