# Generated by Django 4.2.2 on 2023-06-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='information',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='information',
            name='contacts',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='information',
            name='addresses',
            field=models.ManyToManyField(to='info.address'),
        ),
        migrations.AddField(
            model_name='information',
            name='contacts',
            field=models.ManyToManyField(to='info.contact'),
        ),
    ]
