# Generated by Django 4.2.2 on 2023-06-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_about_status_remove_information_addresses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
