# Generated by Django 4.2.2 on 2023-06-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_address_information_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
