# Generated by Django 4.2.2 on 2023-06-16 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_about_active_alter_about_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='status',
        ),
        migrations.RemoveField(
            model_name='information',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='information',
            name='contacts',
        ),
        migrations.AddField(
            model_name='about',
            name='lists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.aboutlist'),
        ),
        migrations.AddField(
            model_name='information',
            name='addresses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.address'),
        ),
        migrations.AddField(
            model_name='information',
            name='contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.contact'),
        ),
    ]
