# Generated by Django 4.2.2 on 2023-06-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
