# Generated by Django 4.2.3 on 2023-07-13 10:26

import Web.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(default='', null=True, upload_to=Web.utils.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg', 'webp', 'svg', 'bmp'])])),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('Abilitation', 'Abilitation'), ('Accreditation', 'Accreditation'), ('Homologation', 'Homologation')], max_length=25, null=True)),
                ('date', models.DateField(blank=True, default='', null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'List des Merites',
                'db_table': 'accreditation_list',
            },
        ),
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('lists', models.ManyToManyField(related_name='accreditation_to_list', to='accreditation.list')),
            ],
            options={
                'verbose_name_plural': 'Les Accreditations',
                'db_table': 'accreditation_value',
            },
        ),
    ]
