# Generated by Django 4.2.2 on 2023-06-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='type',
            field=models.CharField(choices=[('Abilitation', 'Abilitation'), ('Accreditation', 'Accreditation'), ('Omologation', 'Omologation')], max_length=25, null=True),
        ),
    ]
