# Generated by Django 4.2.2 on 2023-06-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0002_list_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name_plural': 'List des Abilitation, Accreditation, Homologation'},
        ),
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.CharField(choices=[('Abilitation', 'Abilitation'), ('Accreditation', 'Accreditation'), ('Homologation', 'Homologation')], max_length=25, null=True),
        ),
    ]
