# Generated by Django 4.2.2 on 2023-06-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0007_alter_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
