# Generated by Django 4.2.2 on 2023-07-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0008_alter_list_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name_plural': 'List des Merites'},
        ),
        migrations.AlterModelTable(
            name='accreditation',
            table='accreditation_value',
        ),
        migrations.AlterModelTable(
            name='list',
            table='accreditation_list',
        ),
    ]
