# Generated by Django 4.2.2 on 2023-07-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0009_alter_list_options_alter_accreditation_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='lists',
            field=models.ManyToManyField(related_name='accreditation_to_list', to='accreditation.list'),
        ),
    ]
