# Generated by Django 4.2.3 on 2023-07-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Lundi'), ('Tue', 'Mardi'), ('Wed', 'Mercredi'), ('Thu', 'Jeudi'), ('Fri', 'Vendredi'), ('Sat', 'Samedi'), ('Sun', 'Dimanche')], max_length=15)),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
                ('message', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Les Horaires de AHSM',
                'db_table': 'hour',
            },
        ),
    ]
